name: CI

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    # Make sure commit messages follow the conventional commits convention:
    # https://www.conventionalcommits.org
    commitlint:
        name: Lint Commit Messages
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            -   uses: wagoid/commitlint-github-action@v5.3.0

    mypy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Python
                uses: actions/setup-python@v4
            -   name: Install mypy
                run: pip install mypy
            -   name: Run mypy
                uses: sasanquaneuf/mypy-github-action@releases/v1
                with:
                    checkName: 'mypy'   # NOTE: this needs to be the same as the job name
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        test:
            strategy:
                fail-fast: false
                matrix:
                    python-version:
                        - "3.10"
                        - "3.11"
                    os:
                        - ubuntu-latest
                        - windows-latest
                        - macOS-latest
            runs-on: ${{ matrix.os }}
            steps:
                -   uses: actions/checkout@v3
                -   name: Set up Python
                    uses: actions/setup-python@v4
                    with:
                        python-version: ${{ matrix.python-version }}
                -   uses: snok/install-poetry@v1.3.3
                -   name: Install Dependencies
                    run: poetry install
                    shell: bash
                -   name: Test with Pytest
                    run: poetry run pytest
                    shell: bash
        release:
            runs-on: ubuntu-latest
            environment: release
            if: github.ref == 'refs/heads/main'
            needs:
                - test

            steps:
                -   uses: actions/checkout@v3
                    with:
                        fetch-depth: 0
                        persist-credentials: false

                # Run semantic release:
                # - Update CHANGELOG.md
                # - Update version in code
                # - Create git tag
                # - Create GitHub release
                # - Publish to PyPI
                -   name: Python Semantic Release
                    uses: relekang/python-semantic-release@v7.33.2
                    with:
                        github_token: ${{ secrets.GH_TOKEN }}
                        repository_username: __token__
                        repository_password: ${{ secrets.PYPI_TOKEN }}
